postgres:
  database: ${POSTGRES_DB:attendance_db}
  host: ${POSTGRES_HOST:localhost}
  port: ${POSTGRES_PORT:5432}
  user: ${POSTGRES_USER:postgres}
  password: ${POSTGRES_PASSWORD:password}

redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}
  password: ${REDIS_PASSWORD:}