changeLogFile=/home/ubuntu/Attendance_API/migration/db.changelog-master.xml

url=jdbc:postgresql://postgress.saransh.otms.internal:5432/attendance_db
username=postgres
password=password

driver=org.postgresql.Driver
classpath=/home/ubuntu/Attendance_API/lib/postgresql-42.7.2.jar

logLevel=info
